export const GET_TRENDING_DATA_REQUEST = "GET_TRENDING_DATA_REQUEST";
export const GET_TRENDING_DATA_SUCCESS = "GET_TRENDING_DATA_SUCCESS";
export const GET_TRENDING_DATA_FAILURE = "GET_TRENDING_DATA_FAILURE";

//for current data

export const GET_CURRENT_DATA_REQUEST = "GET_CURRENT_DATA_REQUEST";
export const GET_CURRENT_DATA_SUCCESS = "GET_CURRENT_DATA_SUCCESS";
export const GET_CURRENT_DATA_FAILURE = "GET_CURRENT_DATA_FAILURE";

//for current data

export const GET_COMEDY_DATA_REQUEST = "GET_COMEDY_DATA_REQUEST";
export const GET_COMEDY_DATA_SUCCESS = "GET_COMEDY_DATA_SUCCESS";
export const GET_COMEDY_DATA_FAILURE = "GET_COMEDY_DATA_FAILURE";
