export const GET_TRENDING_DATA_REQUEST = "GET_TRENDING_DATA_REQUEST";
export const GET_TRENDING_DATA_SUCCESS = "GET_TRENDING_DATA_SUCCESS";
export const GET_TRENDING_DATA_FAILURE = "GET_TRENDING_DATA_FAILURE";

//for current data

export const GET_CURRENT_DATA_REQUEST = "GET_CURRENT_DATA_REQUEST";
export const GET_CURRENT_DATA_SUCCESS = "GET_CURRENT_DATA_SUCCESS";
export const GET_CURRENT_DATA_FAILURE = "GET_CURRENT_DATA_FAILURE";

//for current data

export const GET_COMEDY_DATA_REQUEST = "GET_COMEDY_DATA_REQUEST";
export const GET_COMEDY_DATA_SUCCESS = "GET_COMEDY_DATA_SUCCESS";
export const GET_COMEDY_DATA_FAILURE = "GET_COMEDY_DATA_FAILURE";

//for featured data

export const GET_FEATURED_DATA_REQUEST = "GET_FEATURED_DATA_REQUEST";
export const GET_FEATURED_DATA_SUCCESS = "GET_FEATURED_DATA_SUCCESS";
export const GET_FEATURED_DATA_FAILURE = "GET_FEATURED_DATA_FAILURE";

//for Historical data

export const GET_HISTORICAL_DATA_REQUEST = "GET_HISTORICAL_DATA_REQUEST";
export const GET_HISTORICAL_DATA_SUCCESS = "GET_HISTORICAL_DATA_SUCCESS";
export const GET_HISTORICAL_DATA_FAILURE = "GET_HISTORICAL_DATA_FAILURE";


//for original data

export const GET_ORIGINAL_DATA_REQUEST = "GET_ORIGINAL_DATA_REQUEST";
export const GET_ORIGINAL_DATA_SUCCESS = "GET_ORIGINAL_DATA_SUCCESS";
export const GET_ORIGINAL_DATA_FAILURE = "GET_ORIGINAL_DATA_FAILURE";

//for Popular data
export const GET_POPULAR_DATA_REQUEST = "GET_POPULAR_DATA_REQUEST";
export const GET_POPULAR_DATA_SUCCESS = "GET_POPULAR_DATA_SUCCESS";
export const GET_POPULAR_DATA_FAILURE = "GET_POPULAR_DATA_FAILURE";

//for kids data

export const GET_KIDS_DATA_REQUEST = "GET_KIDS_DATA_REQUEST";
export const GET_KIDS_DATA_SUCCESS = "GET_KIDS_DATA_SUCCESS";
export const GET_KIDS_DATA_FAILURE = "GET_KIDS_DATA_FAILURE";

//for Drama data

export const GET_DRAMA_DATA_REQUEST = "GET_DRAMA_DATA_REQUEST";
export const GET_DRAMA_DATA_SUCCESS = "GET_DRAMA_DATA_SUCCESS";
export const GET_DRAMA_DATA_FAILURE = "GET_DRAMA_DATA_FAILURE";

