export const GET_TRENDING_DATA_REQUEST = "GET_TRENDING_DATA_REQUEST";
export const GET_TRENDING_DATA_SUCCESS = "GET_TRENDING_DATA_SUCCESS";
export const GET_TRENDING_DATA_FAILURE = "GET_TRENDING_DATA_FAILURE";
